### ISSUE TITLE
Anonymer User löschen oder überarbeiten

### ISSUE THREAD

**Issue by AlexDerAndros** [AlexDerAndros/SVOHG#14]
Die anonymen User könnten bei Firebase Authentification die verbrauchte Benutzeranzahl überschreiten und dann wäre es kostenpflichtig. Darum würde es gut sein, wenn man den anonymen Account löscht oder es so macht, dass nur ein User erstellt wird

![image](https://github.com/AlexDerAndros/SVOHG/assets/126338368/2933307b-9eda-4716-98dc-18a70544cc93)
![image](https://github.com/AlexDerAndros/SVOHG/assets/126338368/ee2fedb9-b5a7-433f-83ae-aaaed09e3cde)

**Comment by Marcodoro** [comment]
Kann ich versuchen aber ich weiß nicht ob man Anonyme User löschen kann ohne die Msg zu löschen.

**Comment by AlexDerAndros** [comment]
Ich würde es einfach mal probieren

**Comment by Marcodoro** [comment]
Zu kompliziert mit Cloud functions
