### ISSUE TITLE
Mehrere Events hinzufügen können

### ISSUE THREAD

**Issue by AlexDerAndros** [AlexDerAndros/SVOHG#17]
Die SV will auch, dass man mehrere Events hinzufügen kann und dass man auch welche löschen kann.

**Comment by Marcodoro** [comment]
Kann ich machen und dann kann man im Admin Dashboard entscheiden wie viele evente. Dann wird das Event einfach durch eine map() oder for each() Funktion ersetzt

**Comment by AlexDerAndros** [comment]
Ja das ist gut! Können wir gerne so machen.
