### ISSUE TITLE
OHG Logo einbauen

### ISSUE THREAD

**Issue by AlexDerAndros** [AlexDerAndros/SVOHG#20]
Das OHG Logo soll irgendwo auf der Seite zu finden sein. Mein Tipp wäre im Menu oder ganz unten, wo Folge uns auf Instagram steht. 

![image](https://github.com/AlexDerAndros/SVOHG/assets/126338368/f5141eba-1810-40da-a32a-20fe56d466f5)

**Comment by Marcodoro** [comment]
Arbeite drann

**Comment by Marcodoro** [comment]
Im header kommt das hin.. Links.

**Comment by Marcodoro** [comment]
Fertig!
