### ISSUE TITLE
Alte Events sollen von der Datenbank aus anzeigt werden

### ISSUE THREAD

**Issue by AlexDerAndros** [AlexDerAndros/SVOHG#26]
Wenn ein Event gelöscht wird, soll das Thema des Events in einer Sammlung gespeichert werden, wo alle alten Events gespeichert sind, aber der Rest der Daten soll gelöscht werden von der Database, die vorher unter dem Event gespeichert waren.

**Comment by Marcodoro** [comment]
Warum?

**Comment by Marcodoro** [comment]
Also ich finde das jetzt nicht so wichtig, ich kann aber alle alten Events selbst in ein Text File rein tuen.
