### ISSUE TITLE
Bug Events Handy Version

### ISSUE THREAD

**Issue by AlexDerAndros** [AlexDerAndros/SVOHG#32]
390 x 844

![image](https://github.com/AlexDerAndros/SVOHG/assets/126338368/a6546ed1-b1c5-45ba-b034-d17a5074f997)
![image](https://github.com/AlexDerAndros/SVOHG/assets/126338368/526a8ea8-2d2d-4d35-9c72-ce165fb59a01)

**Comment by Marcodoro** [comment]
Mache ich heute
