### ISSUE TITLE
This website uses cookies, popup

### ISSUE THREAD

**Issue by Marcodoro** [AlexDerAndros/SVOHG#36]
Am Anfang soll drauf stehen, diese Seite benutzt Cookies, das musst man dahin schreiben habe ich irgendwo gelesen... Und dann da auch hinschreiben was gespeichert wird...

**Comment by Marcodoro** [comment]
Habe nochmal nachgeguckt und Mann musst da mit Cookies machen wegen EU Data Gesetze... Da wird einfach stehen diese Website benutzt Cookies und dann ein paar Optionen ob Cookies erlauben oder nur manche was halt nichts machen wird..

**Comment by Marcodoro** [comment]
Habe nochmal nachgeguckt und Mann musst da mit Cookies machen wegen EU Data Gesetze... Da wird einfach stehen diese Website benutzt Cookies und dann ein paar Optionen ob Cookies erlauben oder nur manche was halt nichts machen wird..

**Comment by Marcodoro** [comment]
Habe ich fur ipad gemacht sieht aber auf handy sehr schlecht aus arbeite ich nachste woche drann, sag mir falls du da fehler findest. Und das ablehnen macht nichts...

**Comment by AlexDerAndros** [comment]
> Sag mir ob du das machen möchtest 

Können wir gerne machen

**Comment by Marcodoro** [comment]
![IMG_20240723_214501.jpg](https://github.com/user-attachments/assets/e6725404-cf18-4bae-b61d-541459540223)

![IMG_20240723_214507.jpg](https://github.com/user-attachments/assets/f483d115-7410-4eba-a3c0-87c198cb9009)

So sieht das auf iPad aus

**Comment by Marcodoro** [comment]
Auf Handy fertig auf iPad muss ich nochmal drauf gucken
