### ISSUE TITLE
Login Password Anzeigen

### ISSUE THREAD

**Issue by Marcodoro** [AlexDerAndros/SVOHG#38]
Wenn man sein password ein tippt und auf den Auge clickt wird das Password unter den Input angezeigt, ich finde es sieht besser aus wenn das so aussieht wie im video

https://github.com/user-attachments/assets/307868a3-25df-4a51-a6b0-8c420ea753f4

https://github.com/user-attachments/assets/a76da0d8-5829-4f46-a214-01af3d04f1ba

https://www.w3schools.com/howto/howto_js_toggle_password.asp

Hier kannst du sehen wie Mann das macht

**Comment by Marcodoro** [comment]
@AlexDerAndros wann hast du Zeit das zu machen?

**Comment by AlexDerAndros** [comment]
Ich bin aktuell im Urlaub
